using System;
using System.Runtime.Serialization;
using FstgWebApi.DataContracts;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;

namespace FstgWebApi.DataModels
{
    public class Score: IScore
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId _id { get; set; }
        //public string Id { get; set; }
        public int UserId { get; set; } = 0;
        public int Value { get; set; }
    }
}