using System;
using System.Runtime.Serialization;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace FstgWebApi.DataContracts
{
    public interface IScore
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        ObjectId _id { get; set; }
        //string Id { get; set; }
        int UserId { get; set; }
        int Value { get; set; }
    }
}
